okta_multidemo/blueprints/developer/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField
from wtforms.validators import DataRequired, Length, Optional


class ClientForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(1, 100)])
    grant_type = SelectField(choices=[('client_credentials', 'Client Credentials'), ('authorization_code', 'Authorization Code (PKCE)')])
    redirect_uri = StringField('Redirect URI')

okta_multidemo/blueprints/admin/views.py
from flask import Blueprint, request, render_template, flash

from ...models import get_model
from ...util import APIClient, OktaAPIClient
from ...util.settings import app_settings
from ...util.decorators import login_required

from ..developer.util import PolicyResource
from .util import auth_admin, auth_o4o

admin_blueprint = Blueprint('admin', 'admin', url_prefix='/admin')


@admin_blueprint.route('/', methods=('GET',))
@login_required
@auth_admin()
def index():
    settings = app_settings()
    return render_template(
        'admin/index.html',
        config=settings
    )


@admin_blueprint.route('/orders', methods=('GET',))
@auth_admin()
def orders():
    settings = app_settings()
    status = request.args.get('status')
    orders = get_model('orders')
    if status:
        data = orders.get({'status': status})
    else:
        data = orders.all()
    return render_template(
        'admin/orders.html',
        orders=data,
        config=settings
    )


@admin_blueprint.route('/users', methods=('GET',))
@auth_o4o('admin.users')
def users():
    # get users via OAuth for Okta instread of SSWS API key
    settings = app_settings()
    api_url = '{}/api/v1'.format(settings['OKTA_BASE_URL'])
    okta = APIClient(api_url, request.cookies.get('o4o_token'))
    okta.api.add_resource(resource_name='users')
    # TODO: get only users assigned to app
    data = okta.api.users.list()
    return render_template(
        'admin/users.html',
        users=data.body,
        config=settings
    )


@admin_blueprint.route('/config', methods=('GET',))
@auth_admin()
def config():
    settings = app_settings()
    if not settings['OKTA_API_KEY']:
        flash(
          'No Okta API key configured. See <a href="https://github.com/udplabs/okta-kotter/tree/master/docs/udp">this documentation</a> for additional configuration information.',
          'danger'
        )
        groups = []
        as_data = []
        event_hooks = []
    else:
        okta = OktaAPIClient(settings['OKTA_BASE_URL'], settings['OKTA_API_KEY'])
        # groups, auth servers + policies, event hooks

        okta.api.add_resource(resource_name='groups')
        groups = okta.api.groups.list().body

        okta.api.add_resource(resource_name='authorizationServers')
        okta.api.add_resource(resource_name='policies', resource_class=PolicyResource)
        as_data = []
        auth_svrs = okta.api.authorizationServers.list()
        for i in auth_svrs.body:
            policies = okta.api.policies.get(i['id'], '').body
            as_data.append({
                'name': i['name'],
                'id': i['id'],
                'issuer': i['issuer'],
                'policies': [{'name': j['name'], 'id': j['id']} for j in policies]
            })

        okta.api.add_resource(resource_name='eventHooks')
        event_hooks = okta.api.eventHooks.list().body

    return render_template(
        'admin/config.html',
        config=settings,
        groups_data=groups,
        as_data=as_data,
        hooks_data=event_hooks
    )

okta_multidemo/blueprints/developer/views.py
"""TODO: docstring."""
import json

import requests

from flask import (
    Blueprint, session, request, render_template, redirect, url_for, flash)
from requests.auth import HTTPBasicAuth

from ...util import OktaAPIClient
from ...util.settings import app_settings

from .util import authorize, create_cc_client, create_pkce_client
from .forms import ClientForm
from ...models import get_model

developer_blueprint = Blueprint(
    'developer', 'developer', url_prefix='/developer')

# NOTE: the reason we store clients in the DB instead of just
#   getting them from Okta is to be able to persist the client secret


@developer_blueprint.route('/', methods=('GET',))
@authorize()
def index(user_id=None):
    """TODO: docstring."""
    settings = app_settings()
    client = get_model('clients')
    clients = client.all()
    subdomain = session.get('subdomain')
    m_tenant = get_model('tenants')
    tenant = m_tenant.get({'name': subdomain})[0]
    for i in clients:
        i.update(
            {'client_name': i['client_name'].replace(
                settings['OKTA_RESOURCE_PREFIX'], ''
            )}
        )
    return render_template(
        'blueprints/developer/index.html',
        clients=clients,
        issuer=tenant['OKTA_ISSUER'],
        config=settings
    )


# TODO: REST-ify clients

@developer_blueprint.route('/create-client', methods=('GET', 'POST'))
@authorize()
def create_client(user_id=None):
    """TODO: docstring."""
    settings = app_settings()
    form = ClientForm()
    if request.method == 'POST':
        if form.validate():
            client_name = form.name.data
            grant_type = form.grant_type.data
            if grant_type == 'client_credentials':
                create_cc_client(
                    settings['OKTA_RESOURCE_PREFIX'] + client_name,
                    grant_type,
                    user_id,
                    form.redirect_uri.data,
                    settings
                )
            else:  # PKCE
                create_pkce_client(
                    settings['OKTA_RESOURCE_PREFIX'] + client_name,
                    user_id,
                    settings['FF_PORTFOLIO_CLIENT_GROUP'],
                    form.redirect_uri.data,
                    settings)
            return redirect(url_for('developer.index'))
        else:
            flash('Invalid form data.')
    resp = render_template(
        'blueprints/developer/form.html', form=form, config=settings)
    return resp


@developer_blueprint.route('/delete-client', methods=('GET',))
@authorize()
def delete_client(user_id=None):
    """TODO: docstring."""
    settings = app_settings()
    okta = OktaAPIClient(
        settings['OKTA_BASE_URL'],
        settings['OKTA_API_KEY'],
        'oauth2'
    )
    client_id = request.args.get('client_id')
    okta.api.add_resource(resource_name='clients')
    okta.api.clients.destroy(client_id)
    clients = get_model('clients')
    # FIXME: should be able to use local_id
    clients.delete('client_id', client_id)
    return redirect(url_for('developer.index'))


@developer_blueprint.route('/test-client', methods=('POST',))
@authorize()
def test_client(user_id=None):
    """TODO: docstring."""
    client_id = request.form['client_id']
    client_secret = request.form['client_secret']
    client_name = request.form['client_name']
    url = '{}/v1/token'.format(app_settings()['OKTA_ISSUER'])
    auth = HTTPBasicAuth(client_id, client_secret)
    headers = {
        'accept': 'application/json',
        'content-type': 'application/x-www-form-urlencoded',
    }
    data = {
        'grant_type': 'client_credentials',
        'scope': 'products:read',
    }
    req = requests.post(
        url,
        headers=headers,
        data=data,
        auth=auth
    )
    resp = render_template(
        'blueprints/developer/test.html',
        token_resp=json.dumps(req.json()),
        client_id=client_id,
        client_secret=client_secret,
        client_name=client_name,
        config=app_settings()
    )
    return resp

okta_multidemo/blueprints/events/views.py
import json
from urllib.parse import urlparse

from flask import request, jsonify, render_template, url_for, redirect, flash
from flask_cors import cross_origin

from ..admin.util import auth_o4o
from ..admin.views import admin_blueprint
from ..api.api import api_blueprint
from ...util import APIClient
from ...util.settings import app_settings
from ...models import get_model


@admin_blueprint.route('/events', methods=('GET',))
@auth_o4o('admin.events')  # NOTE: requires okta.eventHooks.read
def events():
    settings = app_settings()
    hook_id = settings['FF_EVENTS_HOOK_ID']
    if not hook_id:
        flash('No event hook configured.', 'danger')
        hooks = []
        admin_url = ''
    else:
        api_url = '{}/api/v1'.format(settings['OKTA_BASE_URL'])
        okta = APIClient(api_url, request.cookies.get('o4o_token'))
        okta.api.add_resource(resource_name='eventHooks')
        data = okta.api.eventHooks.retrieve(hook_id)
        admin_url_segs = settings['OKTA_BASE_URL'].split('.')
        admin_url = admin_url_segs[0] + '-admin.' + '.'.join(
            [admin_url_segs[1], admin_url_segs[2]])
        hooks = data.body['events']['items']
    return render_template(
        'events/index.html',
        hooks=hooks,
        admin_url=admin_url,
        config=app_settings()
    )


@api_blueprint.route('/events', methods=['GET', 'POST'])  # noqa
@cross_origin()  # TODO: whitelist Okta domain
def events_api():
    subdomain = urlparse(request.url).hostname.split('.')[0]
    event_obj = get_model('events', subdomain)
    if request.method == 'POST':
        data = json.loads(request.get_data())
        event = data['data']['events'][0]
        obj = {
            'eventType': event['eventType'],
            'displayMessage': event['displayMessage'],
            'severity': event['severity'],
            'ipAddress': event['client']['ipAddress'],
            'published': event['published'],
            'uuid': event['uuid'],
        }
        event_obj.add(obj)
    else:
        event_hook_verify_code = request.headers.get(
            'X-Okta-Verification-Challenge', None)
        if event_hook_verify_code:
            return json.dumps({'verification': event_hook_verify_code})
        data = event_obj.all()
    return jsonify(data)


@admin_blueprint.route('/events-clear', methods=['GET'])
def events_clear():
    events = get_model('events')
    events.purge()
    return redirect(url_for('admin.events'))

okta_multidemo/blueprints/portfolio/views.py
from collections import Counter

from flask import (
    session, render_template, Blueprint, redirect, url_for, request, flash
)

from .util import get_api_client
from ..admin.util import auth_o4o
from ...util.settings import app_settings
from ...models import get_model

portfolio_blueprint = Blueprint('portfolio', 'portfolio', url_prefix='/portfolio')


@portfolio_blueprint.route('/', methods=('GET',))
@auth_o4o('portfolio.index')
def index(user_id=None):
    # TODO: use API rather than accessing models directly
    settings = app_settings()
    order = get_model('orders')
    orders = []
    images = {}
    for i in order.get({'userId': session['user_id']}):
        images[i['productTitle']] = i['productImage']
        # FIXME: ^^^ ugh kludgy way of getting images into page
        orders.append(i['productTitle'])
    order_list = list(zip(Counter(orders).keys(), Counter(orders).values()))
    # TODO: only return items with status "complete"?
    if len(order_list) == 0:
        flash(
            'You have not yet added any orders to your portfolio.',
            'info')
    try:
        okta_api = get_api_client()
        grants_resp = okta_api.grants.list(session['user_id']).body
        grants = []
        for grant in grants_resp:
            grants.append({
                'id': grant['id'],
                'client_title': grant['_links']['client']['title'].replace(
                    settings['OKTA_RESOURCE_PREFIX'], ''
                ),
                'scope_title': grant['_links']['scope']['title'],
            })
    except ValueError:
        grants = []
        flash(
            'Failed to get grants for consent: Is API_ACCESS_MANAGEMENT_CONSENT feature flag configured in your tenant?',
            'danger')

    return render_template(
        'blueprints/portfolio/index.html',
        orders=order_list,
        images=images,
        grants=grants,
        config=settings
    )


@portfolio_blueprint.route('/revoke', methods=('GET',))
@auth_o4o('portfolio.revoke_consent')
def revoke_consent():
    """TODO: docstring."""
    grant_id = request.args.get('grant_id')
    okta_api = get_api_client()
    okta_api.grants.delete(session['user_id'], grant_id)
    return redirect(url_for('portfolio.index'))

okta_multidemo/templates/blueprints/developer/form.html
{% extends 'base.html' %}

{% block content %}
<h2>Create client</h2>
<form action="" method="POST">
  <div class="form-group">
    <label for="name">Name</label>
    {{ form.name(class_="form-control", id="name", placeholder="Enter client name") }}
    <small id="emailHelp" class="form-text text-muted"></small>
  </div>
  <div class="form-group">
    <label for="grant_type">Grant type</label>
    {{ form.grant_type(class_="form-control", id="grant_type", placeholder="") }}
  </div>
  <div class="form-group">
    <label for="redirect_uri">Redirect URI</label>
    {{ form.redirect_uri(class_="form-control", id="name", placeholder="Enter Redirect URI (Authz Code PKCE only)") }}
    <small id="emailHelp" class="form-text text-muted"></small>
  </div>
  {{ form.csrf_token }}
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

okta_multidemo/templates/blueprints/developer/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Developer</h2>

<div class="card">
  <div class="card-header">
    <strong>Authorization Server info</strong>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Authorize URI: <code>{{ issuer }}/v1/authorize</code></li>
    <li class="list-group-item">Token URI: <code>{{ issuer }}/v1/token</code></li>
  </ul>
</div>
<br />

<a href="{{ url_for('developer.create_client') }}"><button class="btn btn-success" type="submit">Add OAuth 2.0 client</button></a>
<br /><br />

<span id="alert"></span>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Client ID</th>
      <th scope="col">Client Secret</th>
      <th scope="col">OAuth 2.0 Grant Type</th>
      <th scope="col" colspan="2">Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for client in clients %}
    <tr>
      <td>{{ client.client_name }}</td>
      <td>{{ client.client_id }}</th>
      <td>{{ client.client_secret }}</th>
      <td>{{ client.grant_types.0 }}</th>
      <td>
        <a href="{{ url_for('developer.delete_client', id=client.id, client_id=client.client_id) }}" class="btn btn-danger" role="button" aria-pressed="true"><i class="fa fa-remove"></i></a>
      </td>
      <td>{% if client.grant_types.0 == 'client_credentials' %}
        <button class="btn btn-dark" role="button" aria-pressed="true" onClick="redirect('{{ client.client_id }}', '{{ client.client_secret }}', '{{ client.client_name }}');"><i class="fa fa-desktop"></i></button>
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<form id="redirForm" method="POST" action="{{ url_for('developer.test_client') }}">
  <input type="hidden" name="client_id" value="" />
  <input type="hidden" name="client_secret" value="" />
  <input type="hidden" name="client_name" value="" />
</form>
{% endblock %}
{% block add_js %}
<script>
  function redirect(clientId, clientSecret, clientName) {
    var form = document.getElementById("redirForm");
    form.elements[0].value = clientId;
    form.elements[1].value = clientSecret;
    form.elements[2].value = clientName;
    form.submit();
  }
</script>

{% endblock %}

okta_multidemo/templates/blueprints/developer/test.html
{% extends 'base.html' %}
{% block content %}
<h2>Test client: {{ client_name }}</h2>
<pre style="background-color:#555;font-size:12px;" id="output">
</pre>
{% endblock %}
{% block add_js %}
<script src="{{ config.STATIC_URL }}/js/util.js"></script>
<script>
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

function render(data) {
  output.innerHTML += '\n<span style="color:aqua;font-weight:bold;">' + JSON.stringify(data.data, null, 4) + '</span>';
}

document.addEventListener('DOMContentLoaded', async function() {
  var outputElem = document.getElementById('output');
  outputElem.innerHTML = `$ export TEMP_B64_AUTH=\`echo -n {{ client_id }}:{{ client_secret }} | base64\`
$ curl -X POST {{ config.OKTA_ISSUER }}/v1/token \\
-H 'Accept:application/json' \\
-H "Authorization:Basic $TEMP_B64_AUTH" \\
-H 'Content-type:application/x-www-form-urlencoded' \\
-d 'grant_type=client_credentials' \ \\
-d 'scope=products:read'
`;
  await sleep(1500);
  var token_data = JSON.parse('{{ token_resp|safe }}');
  outputElem.innerHTML += '\n<span style="color:aqua;font-weight:bold;">' + JSON.stringify(token_data, null, 4) + '</span>';
  await sleep(1500);
  outputElem.innerHTML += "\n\n$ curl -X GET http://localhost:5000/api/products \\\n-H 'Authorization:Bearer " +  token_data.access_token + "'\n"
  await sleep(1500);
  var result = ajax('{{ config.API_URL }}/products', 'GET', null, render, token_data.access_token);

});
</script>
{% endblock %}