okta_multidemo/models/base.py
class Model(object):
    TYPE = ''

    def __init__(self, db, tenant):
        pass

    def all_(self):
        pass

    def all(self):
        pass

    def get(self, condition=None):
        pass

    def add(self, data):
        pass

    def update(self, data, condition=None):
        pass

    def delete(self, key, value):
        pass

    def purge(self):
        pass

okta_multidemo/blueprints/admin/views.py
from flask import Blueprint, request, render_template, flash

from ...models import get_model
from ...util import APIClient, OktaAPIClient
from ...util.settings import app_settings
from ...util.decorators import login_required

from ..developer.util import PolicyResource
from .util import auth_admin, auth_o4o

admin_blueprint = Blueprint('admin', 'admin', url_prefix='/admin')


@admin_blueprint.route('/', methods=('GET',))
@login_required
@auth_admin()
def index():
    settings = app_settings()
    return render_template(
        'admin/index.html',
        config=settings
    )


@admin_blueprint.route('/orders', methods=('GET',))
@auth_admin()
def orders():
    settings = app_settings()
    status = request.args.get('status')
    orders = get_model('orders')
    if status:
        data = orders.get({'status': status})
    else:
        data = orders.all()
    return render_template(
        'admin/orders.html',
        orders=data,
        config=settings
    )


@admin_blueprint.route('/users', methods=('GET',))
@auth_o4o('admin.users')
def users():
    # get users via OAuth for Okta instread of SSWS API key
    settings = app_settings()
    api_url = '{}/api/v1'.format(settings['OKTA_BASE_URL'])
    okta = APIClient(api_url, request.cookies.get('o4o_token'))
    okta.api.add_resource(resource_name='users')
    # TODO: get only users assigned to app
    data = okta.api.users.list()
    return render_template(
        'admin/users.html',
        users=data.body,
        config=settings
    )


@admin_blueprint.route('/config', methods=('GET',))
@auth_admin()
def config():
    settings = app_settings()
    if not settings['OKTA_API_KEY']:
        flash(
          'No Okta API key configured. See <a href="https://github.com/udplabs/okta-kotter/tree/master/docs/udp">this documentation</a> for additional configuration information.',
          'danger'
        )
        groups = []
        as_data = []
        event_hooks = []
    else:
        okta = OktaAPIClient(settings['OKTA_BASE_URL'], settings['OKTA_API_KEY'])
        # groups, auth servers + policies, event hooks

        okta.api.add_resource(resource_name='groups')
        groups = okta.api.groups.list().body

        okta.api.add_resource(resource_name='authorizationServers')
        okta.api.add_resource(resource_name='policies', resource_class=PolicyResource)
        as_data = []
        auth_svrs = okta.api.authorizationServers.list()
        for i in auth_svrs.body:
            policies = okta.api.policies.get(i['id'], '').body
            as_data.append({
                'name': i['name'],
                'id': i['id'],
                'issuer': i['issuer'],
                'policies': [{'name': j['name'], 'id': j['id']} for j in policies]
            })

        okta.api.add_resource(resource_name='eventHooks')
        event_hooks = okta.api.eventHooks.list().body

    return render_template(
        'admin/config.html',
        config=settings,
        groups_data=groups,
        as_data=as_data,
        hooks_data=event_hooks
    )

okta_multidemo/templates/401.html
{% extends 'base_error.html' %}

{% block content %}
    <div class="cover"><h1>Unauthorized! <small>401</small></h1><p class="lead">Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response.</p>
    <p><a href="/">Home</a></p>
  </div>
{% endblock %}

okta_multidemo/templates/apps.html
{% extends 'base.html' %}

{% block content %}
<div class="card-deck">
{% for app in apps %}
  {% if app._links.appLinks %}
  <a class="no-loader" href="{{ app._links.appLinks.0.href }}" target="_NEW">
  <span style="display: block;" class="card">

    <div class="card-body">
      <h5 class="card-title"><img src="{{ app._links.logo.0.href }}" alt="{{ app.label }}" /> {{ app.label }}</h5>
    </div>

  </span>
  </a>
  {% endif %}
{% endfor %}
</div>
{% endblock %}

okta_multidemo/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico"> -->

    <title>{{ config.SITE_TITLE }}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/starter-template/">

    <!-- Bootstrap core CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

    <link href="{{ config.STATIC_URL }}/css/loader.css" rel="stylesheet">
    {% block add_css %}{% endblock %}

    <!-- Custom styles for this template -->
    <link href="{{ config.STATIC_URL }}/css/starter-template.css" rel="stylesheet">
    <style>
    .home-body-image {
      background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url("{{ config.THEME_URI }}/bg.jpg");
    }
    .navbar {
      /* BELOW USES BG IMAGE FOR NAV BAR */
      background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url("{{ config.THEME_URI }}/bg-nav.jpg");
      background-size: cover;
      /* BELOW MAKES NAV BG IMAGE GRAYSCALE */
      /* -webkit-filter: grayscale(100%); filter: grayscale(100%); */
      /* BELOW USES GRADIENT COLOR INSTEAD OF IMAGE */
      /*background-image: linear-gradient(15deg, #13547a 0%, #80d0c7 100%);*/
    }
    </style>

  </head>

<body class="{{ body_class }}">

  <!-- LOADER -->
  <div class="loader-body done" id="loader">
    <div class="loader"></div>
  </div>
  <!-- LOADER END -->


    <nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
      <a class="navbar-brand" href="/"><img src="{{ config.THEME_URI }}/icon.png" class="img-fluid" style="max-height:25px" />&nbsp;{{ config.SITE_TITLE }}</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          {% if session.username %}
          <li class="nav-item"><!-- class="active" -->
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li>
            <a class="nav-link" href="/products">{{ config.ITEMS_TITLE }}</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Tools</a>
            <div class="dropdown-menu" aria-labelledby="dropdown02">
              {% if session.is_admin %}<a class="dropdown-item" href="{{ url_for('admin.index') }}">Admin</a>{% endif %}
              {% if config.FF_PORTFOLIO %}<a class="dropdown-item" href="{{ url_for('portfolio.index') }}">Portfolio/Consent</a>{% endif %}
              {% if config.FF_DEVELOPER %}<a class="dropdown-item" href="{{ url_for('developer.index') }}">Developer</a>{% endif %}
              {% if config.FF_EVENTS %}<a class="dropdown-item" href="{{ url_for('admin.events') }}">Event Hooks</a>{% endif %}
            </div>
          </li>





          {% else %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Log In</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="{{ url_for('auth.login') }}">Log In (Okta-hosted)</a>
              <h6 class="dropdown-header">OKTA SIGN IN WIDGET</h6>
              <a class="dropdown-item" href="/login-widget">Log In (Authz Code)</a>
              <a class="dropdown-item" href="/login-implicit">Log In (Implicit)</a>
              <a class="dropdown-item" href="/login-social">Log In (Social/IdP)</a>
              <a class="dropdown-item" href="/login-idp-disco">Log In (IdP Disco)</a>
              <a class="dropdown-item" href="/login-custom-css">Log In (Custom CSS)</a>
              <h6 class="dropdown-header">CUSTOM</h6>
              <a class="dropdown-item" href="/login-custom">Log In (Custom Form)</a>
            </div>
          </li>

          {% endif %}
        </ul>
<!--         <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
 -->
          <ul style="float:right" class="navbar-nav mr-auto" >
          {% if session.username %}
              <li class="nav-item" style="color:#fff">
                <a class="nav-link" href="/profile"><i class="fa fa-user"></i> {{ session.name }}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/apps">Apps</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">Log out</a>
              </li>
          {% else %}
            <span style="width:300px"></span><!-- FIXME: why doesn't Help button flush right -->
          {% endif %}
              <li class="nav-item" style="margin-left:20px;">
                <button type="button" class="btn btn-warning btn-sm" data-toggle="modal" data-target="#helpModal" style="margin-top:5px">
                  <i class="fa fa-graduation-cap"></i> Learn
                </button>
              </li>
          </ul>

</div>
    </nav>

    <main role="main" class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% for category, message in messages %}
<div class="alert alert-{{ "primary" if category == "message" else category }}" role="alert">
  {{ message|safe }}
</div>
            {% endfor %}
        {% endwith %}
        {% block content %}{% endblock %}

    </main>
    {% include 'partials/help.html' %}
    {% if config.ENV == 'development' %}
    <div id="bottom-right"><a href="{{ url_for('reset') }}?logout=1"><button class="btn btn-outline-danger btn-sm" type="submit">Reset</button></a></div>
    {% endif %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <script src="{{ config.STATIC_URL }}/js/loader.js"></script>
    {% block add_js %}{% endblock %}
  </body>
</html>

okta_multidemo/templates/index.html
{% extends 'base.html' %}

{% block content %}
      <div class="starter-template text-light">
        <h1>Welcome to {{ config.SITE_TITLE }}</h1>
        {% if not session.username %}
        <a href="{{ url_for('auth.login') }}"><button class="btn btn-primary" type="submit">Log In</button></a>
        <br /><br />
        <p>If you do not have an account, click <a href="/subscribe">here</a> to join.</p>
        {% else %}
        {% include 'partials/tokens.html' %}
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#tokenModal">
          Tokens
        </button>
        {% endif %}
      </div>
{% endblock %}

okta_multidemo/templates/items-rest.html
{% extends 'base.html' %}
{% block content %}
<div class="card-deck" id="card-container">
</div>

{% endblock %}

{% block add_js %}
<script src="/static/js/util.js"></script>
<script>
// TODO: move to a JS file?
function get_card_html(item, theme_mode, theme) {
  var template = `
    <div class="card" style="max-width:300px">
      ${item.target === 'PREMIUM' ? '<div class="ribbon-wrapper"><div class="ribbon green">PREMIUM</div></div>' : ''}
      <img class="card-img-top img-fluid" src="/static/img/${theme_mode}/${theme}/items/${item.image}" alt="${item.title}" style="max-width:150px;height:auto">
      <div class="card-body">
        <h5 class="card-title">${item.title}</h5>
        <p class="card-text"></p>
      </div>
      <div class="card-footer">
        <small class="text-muted"><span id="itemCt-${item.itemId}">${item.count}</span> available</small>
        <button id="btn-${item.itemId}" type="button" class="btn btn-primary btn-sm" style="float:right;" onclick="itemAction(${item.itemId}, '{{ config.API_URL }}', '{{ session.user_id }}');">{{ config.ITEMS_ACTION_TITLE }}</button>
      </div>
    </div>
  `;
  return template;
}

function render(data) {
  var content = '';
  data.data.forEach(item => {
    content = content + get_card_html(item, '{{ config.THEME_MODE }}', '{{ config.THEME_LABEL }}');
  });
  var container = document.getElementById('card-container');
  container.innerHTML = content;
}

var accessToken = document.cookie.replace(/(?:(?:^|.*;\s*)access_token\s*\=\s*([^;]*).*$)|^.*$/, "$1");
var result = ajax('http://localhost:5000/api/items', 'GET', null, render, accessToken);

</script>
{% endblock %}

okta_multidemo/templates/items-spa.html
{% extends 'base.html' %}

{% block content %}
<h1>Items 2</h1>

<div class="card-deck" id="card-container">
</div>

{% endblock %}

{% block add_js %}
<script src="/static/js/util.js"></script>
<script>
// TODO: move to a JS file
function get_card_html(item) {
  var template = `
    <div class="card">
      <img class="card-img-top" src="/static/img/themes/books/items/${item.image}" alt="${item.title}">
      <div class="card-body">
        <h5 class="card-title">${item.title}</h5>
        <p class="card-text"></p>
      </div>
      <div class="card-footer">
        <small class="text-muted">Last updated 3 mins ago</small>
      </div>
    </div>
  `;
  return template;
}

function render(data) {
  var content = '';
  data.data.forEach(item => {
    content = content + get_card_html(item);
  });
  var container = document.getElementById('card-container');
  container.innerHTML = content;
}

var accessToken = document.cookie.replace(/(?:(?:^|.*;\s*)access_token\s*\=\s*([^;]*).*$)|^.*$/, "$1");
var result = ajax('http://localhost:5000/api/items', 'GET', null, render, accessToken);

</script>
{% endblock %}

okta_multidemo/templates/items.html
{% extends 'base.html' %}

{% block content %}

<span id="alert"></span>

<div class="card-deck">
  {% for item in items %}
  <div class="card" style="max-width:300px">
    {% if item.target == 'PREMIUM' %}
    <div class="ribbon-wrapper">
        <div class="ribbon green">PREMIUM</div>
    </div>
    {% endif %}
    <img class="card-img-top img-fluid" src="/static/img/{{ config.THEME_MODE }}/{{ config.THEME_LABEL }}/items/{{ item.image }}" alt="{{ item.title }}" style="max-width:150px;height:auto">
    <div class="card-body">
      <h5 class="card-title">{{ item.title }}</h5>
      <p class="card-text"></p>
    </div>
    <div class="card-footer">
      <small class="text-muted"><span id="itemCt-{{ item.itemId }}">{{ item.count }}</span> available</small>
      <button id="btn-{{ item.itemId }}" type="button" class="btn btn-primary btn-sm" style="float:right;" onclick="itemAction({{ item.itemId }}, '{{ config.API_URL }}', '{{ session.user_id }}');">{{ config.ITEMS_ACTION_TITLE }}</button>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}
{% block add_js %}
<script src="/static/js/util.js"></script>
{% endblock %}

okta_multidemo/templates/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Login</h1>
<form action="" method="POST">
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    {{ form.username(class_="form-control", id="username", placeholder="Enter email") }}
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    {{ form.password(class_="form-control", id="password", placeholder="Password", type="password") }}
  </div>
  {{ form.csrf_token }}
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

okta_multidemo/templates/products-rest.html
{% extends 'base.html' %}
{% block content %}
<span id="alert"></span>
<div class="card-deck" id="card-container">
</div>

{% endblock %}

{% block add_js %}
<script src="{{ config.STATIC_URL }}/js/util.js"></script>
<script>
// TODO: move to a JS file?
function get_card_html(item, theme_uri) {
  var template = `
    <div class="card" style="max-width:300px">
      ${item.target === 'PREMIUM' ? '<div class="ribbon-wrapper"><div class="ribbon green">PREMIUM</div></div>' : ''}
      <img class="card-img-top img-fluid" src="${item.image}" alt="${item.name}" style="max-width:150px;height:auto">
      <div class="card-body">
        <h5 class="card-title">${item.name}</h5>
        <p class="card-text"></p>
      </div>
      <div class="card-footer">
        <small class="text-muted"><span id="itemCt-${item.itemId}">${item.count}</span> available</small>
        <button id="btn-${item.itemId}" type="button" class="btn btn-primary btn-sm" style="float:right;" onclick="itemAction('${item.itemId}', '{{ config.API_URL }}', '{{ session.user_id }}');">{{ config.ITEMS_ACTION_TITLE }}</button>
      </div>
    </div>
  `;
  return template;
}

function render(data) {
  if (data.error) {
    showAlert('danger', 'An error occurred: ' + data.error.description);
  }
  var content = '';
  data.data.forEach(item => {
    content = content + get_card_html(item, '{{ config.THEME_URI }}');
  });
  var container = document.getElementById('card-container');
  container.innerHTML = content;
}

var accessToken = document.cookie.replace(/(?:(?:^|.*;\s*)access_token\s*\=\s*([^;]*).*$)|^.*$/, "$1");
var result = ajax('{{ config.API_URL }}/products', 'GET', null, render, accessToken);

</script>
{% endblock %}

okta_multidemo/templates/products.html
{% extends 'base.html' %}

{% block content %}

<span id="alert"></span>

<div class="card-deck">
  {% for item in items %}
  <div class="card" style="max-width:300px">
    {% if item.target == 'PREMIUM' %}
    <div class="ribbon-wrapper">
        <div class="ribbon green">PREMIUM</div>
    </div>
    {% endif %}
    <img class="card-img-top img-fluid" src="{{ item.image }}" alt="{{ item.name }}" style="max-width:150px;height:auto">
    <div class="card-body">
      <h5 class="card-title">{{ item.name }}</h5>
      <p class="card-text"></p>
    </div>
    <div class="card-footer">
      <small class="text-muted"><span id="itemCt-{{ item.itemId }}">{{ item.count }}</span> available</small>
      <button id="btn-{{ item.itemId }}" type="button" class="btn btn-primary btn-sm" style="float:right;" onclick="itemAction('{{ item.itemId }}', '{{ config.API_URL }}', '{{ session.user_id }}');">{{ config.ITEMS_ACTION_TITLE }}</button>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}
{% block add_js %}
<script src="{{ config.STATIC_URL }}/js/util.js"></script>
{% endblock %}

okta_multidemo/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<h1>Profile</h1>
TODO
{% endblock %}

okta_multidemo/templates/subscribe.html
{% extends 'base.html' %}

{% block content %}
<h1>Signup</h1>
TODO
{% endblock %}

okta_multidemo/templates/tools.html
{% extends 'base.html' %}

{% block content %}
<div class="card-deck">
{% for app in apps %}
<!-- <span style="padding:10px;margin-bottom:10px;">
<button type="button" class="btn btn-outline-secondary btn-lg"><img src="{{ app._links.logo.0.href }}" /> {{ app.label }}</button>
</span>
 -->
  <a href="{{ app._links.appLinks.0.href }}" target="_NEW">
  <span style="display: block;" class="card">

    <div class="card-body">
      <h5 class="card-title"><img src="{{ app._links.logo.0.href }}" alt="{{ app.label }}" /> {{ app.label }}</h5>
    </div>

  </span>
  </a>
<!--
  <div class="card">
    <img src="{{ app._links.logo.0.href }}" /> {{ app.label }}
  </div>
 -->

{% endfor %}
</div>
{% endblock %}